resume: /public_bme/data/linxin_debug/Loss/for_debug_pth/_train_lccd_sr_batch_size_2/20241107_190328/epoch-20.pth
ask_user: false
remove_save_path: false
train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/train/modality1_img.txt
      root_path_2: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/train/modality2_img.txt
      prompt_D1_M1: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/train/modality1_prompt.txt
      prompt_D1_M2: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/train/modality2_prompt.txt
      repeat: 1
      cache: in_memory
  wrapper_paired:
    name: sr-implicit-paired
    args:
      augment: true
      sample_q: 8000
      scale_min: 1
      scale_max: 3
  wrapper_full:
    name: sr-implicit-full
    args:
      augment: true
      sample_q: 8000
  batch_size: 2
val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/val/modality1_img.txt
      root_path_2: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/val/modality2_img.txt
      prompt_D1_M1: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/val/modality1_prompt.txt
      prompt_D1_M2: /home_data/home/linxin2024/code/3DMedDM_v2/dataset_10_centers/all_paired/val/modality2_prompt.txt
      repeat: 1
      cache: in_memory
  wrapper_paired:
    name: sr-implicit-paired
    args:
      augment: true
      sample_q: 8000
      scale_min: 1
      scale_max: 3
  wrapper_full:
    name: sr-implicit-full
    args:
      augment: true
      sample_q: 8000
  batch_size: 2
model_G:
  name: lccd
  args:
    encoder_spec:
      name: resencoder-256
      args:
        no_upsampling: true
    no_imnet: false
model_D:
  name: NLDiscri
  args:
    in_dim: 8000
    out_dim: 864
    hidden_list:
    - 256
    - 256
    - 256
    - 256
optimizer_G:
  name: adam
  args:
    lr: 0.0001
optimizer_D:
  name: adam
  args:
    lr: 0.0001
epoch_max: 550
epoch_threshold: 500
multi_step_lr:
  milestones:
  - 100
  - 220
  - 300
  - 350
  - 400
  - 500
  gamma: 0.5
epoch_val: 10
epoch_save: 10
training_params:
  patch_size:
  - 32
  - 32
  - 32
  overlap_ratio: 0.25
  patch_batch_size: 32
